// Public API namespace — Phase 5, Wave 2 (docs/plans/phase-5.md task #2).
//
// Exposed on the SDK as `client.public.*`. Each resource API is a thin typed
// wrapper over the shared ApiClient http core (envelope unwrap + error handling).
// Anonymous endpoints do NOT set X-CSRF-Token or require cookieAuth.
// Self-service endpoints (enroll.*) require the session issued by register().
//
// Namespace layout:
//   client.public.programs.*  — P-1 (list), P-2 (getBySlug)
//   client.public.leads.*     — P-3 (capture)
//   client.public.coupons.*   — P-5 (validate)
//   client.public.auth.*      — P-6 (register)
//   client.public.enroll.*    — P-7 (createOrder), P-8 (checkout), P-9 (verify)
//   client.public.bookings.*  — P-4 (createPublic — reused from crm/bookings)
//
// P-4 (POST /public/bookings) is on `client.crm.bookings.createPublic()` (P2 reuse).
// It is also aliased here as `client.public.bookings.create()` for convenience in the
// web app so developers don't need to reach into crm.bookings for a public write.
//
// Security contracts:
//   - client.public.programs.*: unauthenticated GETs. No credentials headers.
//   - client.public.leads.capture(): no auth; captchaToken in body; rate-limited.
//   - client.public.coupons.validate(): no auth; captchaToken in body; rate-limited.
//   - client.public.auth.register(): no auth; captchaToken in body; issues session.
//   - client.public.enroll.*: cookieAuth (session from register()); own-scoped.
//     Idempotency-Key generated by default (crypto.randomUUID()) or caller-supplied.
//     Client MUST supply the same idempotencyKey on retries (not a new one).

import type { ApiClient } from "../http/client.js";
import { PublicProgramsApi } from "./programs.api.js";
import { PublicMentorsApi } from "./mentors.api.js";
import { PublicLeadsApi } from "./leads.api.js";
import { PublicCouponsApi } from "./coupons.api.js";
import { PublicAuthApi } from "./auth.api.js";
import { PublicEnrollApi } from "./enroll.api.js";
import { PublicBookingsApi } from "./bookings.api.js";
import { PublicContentApi } from "./content.api.js";
import { PublicSiteSettingsApi } from "./site-settings.api.js";
import { PublicNewsletterApi } from "./newsletter.api.js";
import { PublicContactApi } from "./contact.api.js";
import { PublicCareersApi } from "./careers.api.js";
import { PublicLandingPagesApi } from "./landing-pages.api.js";
import { PublicLeadFormsApi } from "./lead-forms.api.js";
import { PublicReferralsApi } from "./referrals.api.js";
import { PublicSeoApi } from "./seo.api.js";
import { PublicBundlesApi } from "./bundles.api.js";
import { PublicSearchApi } from "./search.api.js";
import { PublicPayLinkApi } from "./pay-link.api.js";
import { PublicOnboardingApi } from "./onboarding.api.js";

export class PublicApi {
  /** P-1, P-2: Public program catalog (anonymous reads). */
  readonly programs: PublicProgramsApi;
  /** Public mentors directory — active CRM mentors, safe projection (anonymous reads). */
  readonly mentors: PublicMentorsApi;
  /** P-3: Public lead capture from site forms (anonymous write, captcha-gated). */
  readonly leads: PublicLeadsApi;
  /** P-5: Public coupon validation for pricing/checkout (anonymous write, captcha-gated). */
  readonly coupons: PublicCouponsApi;
  /** P-6: Self-service student registration (anonymous → issues session). */
  readonly auth: PublicAuthApi;
  /**
   * P-7, P-8, P-9: Self-service enrollment funnel (requires session from register()).
   * All methods are own-scoped (student acts only on their own order).
   */
  readonly enroll: PublicEnrollApi;
  /** P-4: Book-Free-Slot intake (anonymous write, reuses P2 /public/bookings). */
  readonly bookings: PublicBookingsApi;
  /** Pay-link flow (lifecycle-redesign): token-authorized Razorpay checkout — no session. */
  readonly payLink: PublicPayLinkApi;
  /**
   * Phase 9 Completion (docs/plans/phase-9-completion.md T14) — headless CMS public
   * reads (nested: `content.blog` / `.testimonials` / `.partners` / `.facultyBios` /
   * `.pages` / `.kbArticles`), newsletter subscribe/unsubscribe, contact form, career
   * apply, landing-page render, lead-form config read, referral redeem.
   */
  readonly content: PublicContentApi;
  /**
   * Phase-10 page builder (docs/specs/phase-10-page-builder.md) — all 8 sitewide
   * SiteSetting values (nav/footer/SEO/contact/stats) in one cacheable call. Page-builder
   * pages themselves are read via `content.pages.getBySlug()` (already resolves
   * `live_collection_ref` blocks server-side when `isBuilderManaged=true`).
   */
  readonly siteSettings: PublicSiteSettingsApi;
  readonly newsletter: PublicNewsletterApi;
  readonly contact: PublicContactApi;
  readonly careers: PublicCareersApi;
  readonly landingPages: PublicLandingPagesApi;
  readonly leadForms: PublicLeadFormsApi;
  readonly referrals: PublicReferralsApi;
  /**
   * Phase 9 Completion follow-up (docs T30) — promoted from backend-local schemas.
   * `seo`/`bundles`: per-city SEO landing pages + track/bundle pricing (growth
   * public surface). `search`: CLIENT-SIDE composition over public.programs +
   * public.content.blog — there is no dedicated backend search route (see
   * @repo/types public/search.schemas.ts file header).
   */
  readonly seo: PublicSeoApi;
  readonly bundles: PublicBundlesApi;
  readonly search: PublicSearchApi;
  /**
   * Student onboarding form (onboarding.stimuliiq.com). The question set is authored in the
   * CRM, so `onboarding.getForm()` is what the page renders from — the client bundle
   * hardcodes no questions. File answers (the payment receipt) go through
   * `onboarding.getUploadUrl()` first; only the returned `storageKey` is ever submitted.
   */
  readonly onboarding: PublicOnboardingApi;

  constructor(client: ApiClient) {
    this.programs = new PublicProgramsApi(client);
    this.mentors = new PublicMentorsApi(client);
    this.leads = new PublicLeadsApi(client);
    this.coupons = new PublicCouponsApi(client);
    this.auth = new PublicAuthApi(client);
    this.enroll = new PublicEnrollApi(client);
    this.bookings = new PublicBookingsApi(client);
    this.payLink = new PublicPayLinkApi(client);
    this.content = new PublicContentApi(client);
    this.siteSettings = new PublicSiteSettingsApi(client);
    this.newsletter = new PublicNewsletterApi(client);
    this.contact = new PublicContactApi(client);
    this.careers = new PublicCareersApi(client);
    this.landingPages = new PublicLandingPagesApi(client);
    this.leadForms = new PublicLeadFormsApi(client);
    this.referrals = new PublicReferralsApi(client);
    this.seo = new PublicSeoApi(client);
    this.bundles = new PublicBundlesApi(client);
    this.search = new PublicSearchApi(client);
    this.onboarding = new PublicOnboardingApi(client);
  }
}

export * from "./programs.api.js";
export * from "./mentors.api.js";
export * from "./leads.api.js";
export * from "./coupons.api.js";
export * from "./auth.api.js";
export * from "./enroll.api.js";
export * from "./bookings.api.js";
export * from "./content.api.js";
export * from "./site-settings.api.js";
export * from "./newsletter.api.js";
export * from "./contact.api.js";
export * from "./careers.api.js";
export * from "./landing-pages.api.js";
export * from "./lead-forms.api.js";
export * from "./referrals.api.js";
export * from "./seo.api.js";
export * from "./bundles.api.js";
export * from "./search.api.js";
export * from "./onboarding.api.js";
