// apps/api/src/modules/mentors/dto/index.ts
//
// Re-exports the Phase-8 Mentor zod schemas from @repo/types (docs/04-trd-architecture.md
// §2.2 module template). Never redeclare a shape here — single source of truth stays in
// packages/types/src/crm/mentors.schemas.ts.

export {
  MentorEngagementStatusSchema,
  type MentorEngagementStatus,
  BatchCompletionBucketSchema,
  type BatchCompletionBucket,
  CreateMentorRequestSchema,
  type CreateMentorRequest,
  UpdateMentorRequestSchema,
  type UpdateMentorRequest,
  ListMentorsQuerySchema,
  type ListMentorsQuery,
  MentorAssignedBatchSchema,
  type MentorAssignedBatch,
  MentorSummarySchema,
  type MentorSummary,
  MentorDetailSchema,
  type MentorDetail,
  RestoreMentorRequestSchema,
  type RestoreMentorRequest,
  MentorPhotoUploadUrlRequestSchema,
  type MentorPhotoUploadUrlRequest,
  MentorSocialLinksSchema,
  type MentorSocialLinks,
  AssignMentorToBatchRequestSchema,
  type AssignMentorToBatchRequest,
  MentorBatchAssignmentSchema,
  type MentorBatchAssignment,
  MentorBatchAssignmentListSchema,
  type MentorBatchAssignmentList,
  BatchCompletionSummaryDtoSchema,
  type BatchCompletionSummaryDto,
  BatchCompletionStudentRowSchema,
  type BatchCompletionStudentRow,
  ListBatchCompletionStudentsQuerySchema,
  type ListBatchCompletionStudentsQuery,
  MarkBatchCompleteRequestSchema,
  type MarkBatchCompleteRequest,
  MarkBatchCompleteResponseSchema,
  type MarkBatchCompleteResponse,
  MentorDashboardBatchCardSchema,
  type MentorDashboardBatchCard,
  MentorDashboardDtoSchema,
  type MentorDashboardDto,
} from "@repo/types";
