// Invoices contract — Phase 2, Wave 2 (docs/plans/phase-2.md task #2).
//
// Invoice generation is ASYNC (BullMQ `invoice-gen` queue triggered on payment
// success — backend task #5). The API surface here is:
//   - GET list (Finance / Admin)
//   - GET detail (Finance / Admin)
//   - GET download signed-url stub (returns a pre-signed storage URL or a stub
//     when StorageProvider is not yet configured — P2 uses a stub renderer;
//     full templated PDF is a tracked follow-up per phase-2.md §"Risks #3")
//
// Invoice rows are NEVER created directly via the API — they are created by the
// `invoice-gen` queue worker when a payment is captured. The `status` field
// reflects the generation lifecycle (draft→issued→void). There is no POST or
// PATCH endpoint for invoices in P2.
//
// `tax` is a JSON field (flexible per invoice, varies by GST regime/state).
// Its shape is intentionally open in P2; a strict tax schema can replace it
// when India GST compliance is hardened (post-P2 follow-up).

import { z } from "zod";
import { UuidSchema, IsoDateTimeSchema } from "../common/primitives.js";
import { PageQuerySchema } from "../common/pagination.js";

// ─────────────────────────────────────────────────────────────────────────
// Enums
// ─────────────────────────────────────────────────────────────────────────

export const InvoiceStatusSchema = z.enum(["draft", "issued", "void"]);
export type InvoiceStatus = z.infer<typeof InvoiceStatusSchema>;

// ─────────────────────────────────────────────────────────────────────────
// Sub-schemas
// ─────────────────────────────────────────────────────────────────────────

/**
 * Tax line JSON stored on the invoice row. Shape is intentionally open in P2
 * (India GST compliance is a post-P2 follow-up). Backend serializes whatever
 * the invoice renderer computes; clients treat this as display-only.
 */
export const InvoiceTaxSchema = z
  .record(z.string(), z.unknown())
  .describe(
    "Tax breakdown JSON (open shape in P2 — GST compliance hardening is a post-P2 follow-up). " +
      "May include keys like `cgst`, `sgst`, `igst`, `taxRate`, `taxAmountPaise`.",
  );
export type InvoiceTax = z.infer<typeof InvoiceTaxSchema>;

// ─────────────────────────────────────────────────────────────────────────
// Requests
// ─────────────────────────────────────────────────────────────────────────

/** GET /api/v1/commerce/invoices — filter/paginate invoice list. */
export const ListInvoicesQuerySchema = z
  .object({
    orderId: UuidSchema.optional(),
    studentId: UuidSchema.optional(),
    status: InvoiceStatusSchema.optional(),
    from: z.string().datetime({ offset: true }).optional(),
    to: z.string().datetime({ offset: true }).optional(),
    search: z.string().min(1).max(200).optional().describe("Match by invoice number or student name."),
  })
  .merge(PageQuerySchema)
  .strict();
export type ListInvoicesQuery = z.infer<typeof ListInvoicesQuerySchema>;

// ─────────────────────────────────────────────────────────────────────────
// Response DTOs
// ─────────────────────────────────────────────────────────────────────────

/** Row shape for the invoices list — minimal, no entity leakage. */
export const InvoiceSummarySchema = z.object({
  id: UuidSchema,
  orderId: UuidSchema,
  number: z.string().describe("Unique sequential invoice number per tenant."),
  status: InvoiceStatusSchema,
  issuedAt: IsoDateTimeSchema.nullable(),
  studentName: z.string(),
  programTitle: z.string(),
  amountPaise: z.number().int().min(0).describe("Order amount in integer paise."),
  currency: z.string().length(3),
  createdAt: IsoDateTimeSchema,
});
export type InvoiceSummary = z.infer<typeof InvoiceSummarySchema>;

/** Full invoice detail including tax breakdown. */
export const InvoiceDetailSchema = InvoiceSummarySchema.extend({
  studentId: UuidSchema,
  tax: InvoiceTaxSchema.nullable(),
  storageKey: z
    .string()
    .nullable()
    .describe("Storage object key for the generated PDF. Null until generated by the queue worker."),
  updatedAt: IsoDateTimeSchema,
});
export type InvoiceDetail = z.infer<typeof InvoiceDetailSchema>;

/**
 * Response for GET /api/v1/commerce/invoices/:id/download
 *
 * Returns a pre-signed short-lived URL to download the invoice PDF from
 * object storage. In P2 the StorageProvider may be a stub — in that case
 * `url` is null and `stubMode` is true (the frontend should show an
 * appropriate message instead of a download button).
 */
export const InvoiceDownloadResponseSchema = z.object({
  url: z
    .string()
    .url()
    .nullable()
    .describe("Pre-signed download URL, valid for a short TTL (backend configures TTL). Null in stub mode."),
  expiresAt: IsoDateTimeSchema.nullable().describe("When the pre-signed URL expires. Null in stub mode."),
  stubMode: z
    .boolean()
    .describe("True when StorageProvider is not configured (P2 stub). Frontend should inform user PDF is not yet available."),
});
export type InvoiceDownloadResponse = z.infer<typeof InvoiceDownloadResponseSchema>;

// ─────────────────────────────────────────────────────────────────────────
// Receipt PDF — Phase 9 Completion, T14/T27 (docs/plans/phase-9-completion.md).
// A payment receipt is distinct from the invoice: generated per-CAPTURED-payment
// (not per-order) via `@react-pdf/renderer` -> StorageProvider (BullMQ job, T27),
// GST fields carried on the invoice this receipt corresponds to. Owner (the paying
// student, own-scope) or Finance/Admin (all-scope) may download.
// ─────────────────────────────────────────────────────────────────────────

/** GET /api/v1/commerce/payments/:id/receipt */
export const ReceiptDownloadResponseSchema = z.object({
  url: z.string().url().nullable().describe("Pre-signed short-lived download URL. Null until the PDF render job has completed."),
  expiresAt: IsoDateTimeSchema.nullable(),
  ready: z.boolean().describe("False while the BullMQ PDF-render job is still queued/running (T27); poll until true."),
});
export type ReceiptDownloadResponse = z.infer<typeof ReceiptDownloadResponseSchema>;
