/**
 * MDX type declarations for apps/web.
 *
 * Tells TypeScript that *.mdx files export:
 *   - `default`: a React component (the page body).
 *   - `frontmatter`: the typed frontmatter object (generated by remark-mdx-frontmatter).
 *
 * Importers should cast `frontmatter` to the appropriate typed interface
 * (BlogPostFrontmatter, ContentPageFrontmatter, etc.) from lib/content/types.ts.
 */
declare module "*.mdx" {
  import type { ComponentType } from "react";

  /** MDX body rendered as a React component. */
  const default_export: ComponentType;
  export default default_export;

  /**
   * Frontmatter exported by remark-mdx-frontmatter.
   * Cast to the specific frontmatter type for your content directory.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any -- frontmatter shape varies by content type
  export const frontmatter: Record<string, any>;
}
