// apps/api/src/modules/openapi/openapi.controller.ts
//
// Serves the auth OpenAPI document at GET /api-docs.json (docs/plans/phase-0.md task #8
// deliverable: "Serve OpenAPI at /api-docs.json from @repo/types"). Reads the static
// snapshot `apps/api/openapi/auth.openapi.json` — generated by `pnpm --filter @repo/types
// gen:openapi` from the same zod registry that `generateOpenApiDocument()` builds at
// runtime (packages/types/src/openapi/registry.ts) — rather than importing
// `@repo/types/openapi` directly. The subpath import is deliberately avoided here: that
// package export resolves only under `moduleResolution: bundler/node16/nodenext`, and
// apps/api's NestJS preset (@repo/config/tsconfig/node.json) intentionally stays on
// classic `Node` resolution (CommonJS) because the rest of the dependency graph — `jose`
// (ESM-only) imported via dynamic-style CJS interop, `@repo/types` itself (ESM) — is not
// ready for a wholesale Node16/NodeNext migration; changing that shared preset broke
// every other CJS/ESM interop import across the app. Reading the JSON file keeps the
// route correct without destabilizing the rest of the build. Re-run `pnpm gen:openapi`
// (root script, wired into turbo's build graph) whenever an auth schema changes so this
// file and the live registry never drift.
//
// Registered OUTSIDE the global "api/v1" prefix (see app.module.ts/main.ts) since
// /api-docs.json is a meta endpoint, not a versioned resource.

import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { Controller, Get, InternalServerErrorException } from "@nestjs/common";

const OPENAPI_DOCUMENT_PATH = resolve(__dirname, "../../../openapi/auth.openapi.json");

@Controller("api-docs.json")
export class OpenApiController {
  @Get()
  getDocument(): unknown {
    try {
      const raw = readFileSync(OPENAPI_DOCUMENT_PATH, "utf8");
      return JSON.parse(raw) as unknown;
    } catch {
      throw new InternalServerErrorException({
        code: "openapi.document_unavailable",
        title: "OpenAPI document unavailable",
        detail: "Run `pnpm --filter @repo/types gen:openapi` to regenerate apps/api/openapi/auth.openapi.json.",
      });
    }
  }
}
