// apps/api/src/modules/auth/lib/jwt-keys.ts
//
// Loads the local RS256 keypair generated by `pnpm gen:keys` (infra/scripts/gen-keys.mjs)
// from the paths configured in env (JWT_PRIVATE_KEY_PATH / JWT_PUBLIC_KEY_PATH). Imports
// them as `jose` KeyLike objects once per process (memoized) — never read the PEM files
// per-request.

import { existsSync, readFileSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { importPKCS8, importSPKI, type CryptoKey } from "jose";
import { validateEnv } from "../../../config/env";

const ALG = "RS256" as const;

let cachedPrivateKey: CryptoKey | undefined;
let cachedPublicKey: CryptoKey | undefined;

/**
 * Resolves a repo-root-relative key path (e.g. "./keys/jwt-private.pem", per
 * `.env.example`) regardless of whether the process cwd is the monorepo root or
 * `apps/api` (both are valid depending on how the app is launched: `pnpm dev`
 * from root vs `pnpm --filter @stimuliiq/api dev`). Walks upward from cwd looking
 * for a directory that actually contains the target file, capped at 5 levels to
 * avoid runaway traversal.
 */
function resolveKeyPath(relativePath: string): string {
  if (isAbsolute(relativePath)) return relativePath;

  let dir = process.cwd();
  for (let i = 0; i < 5; i += 1) {
    const candidate = resolve(dir, relativePath);
    if (existsSync(candidate)) return candidate;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fall back to cwd-relative even if not found, so the resulting ENOENT error
  // message points at a sensible path.
  return resolve(process.cwd(), relativePath);
}

export async function loadPrivateKey(): Promise<CryptoKey> {
  if (cachedPrivateKey) return cachedPrivateKey;
  const env = validateEnv();
  const pem = readFileSync(resolveKeyPath(env.JWT_PRIVATE_KEY_PATH), "utf8");
  cachedPrivateKey = await importPKCS8(pem, ALG);
  return cachedPrivateKey;
}

export async function loadPublicKey(): Promise<CryptoKey> {
  if (cachedPublicKey) return cachedPublicKey;
  const env = validateEnv();
  const pem = readFileSync(resolveKeyPath(env.JWT_PUBLIC_KEY_PATH), "utf8");
  cachedPublicKey = await importSPKI(pem, ALG);
  return cachedPublicKey;
}

export const JWT_ALG = ALG;
