// apps/api/src/prisma/audit-context.ts
//
// Request-context seam for the audit extension (docs/05-database-design.md §6).
//
// The audit extension (audit.extension.ts) needs to know "who did this" (actor_id),
// "from where" (ip), and which tenant the mutation belongs to, but Prisma extensions
// have no access to the HTTP request. We bridge that gap with `AsyncLocalStorage`:
// a NestJS interceptor/middleware (owned by backend-builder, Wave 4) is expected to
// call `auditContextStorage.run({ tenantId, actorId, ip }, next)` once per request,
// wrapping the rest of the request pipeline. Every Prisma call made during that
// request (including inside services/guards) will then see the same context via
// `getAuditContext()`.
//
// SEAM FOR BACKEND-BUILDER (Wave 4):
// 1. Create a NestJS middleware or interceptor that runs early in the request
//    lifecycle (after auth has resolved `req.user` / tenant resolution).
// 2. Call:
//      auditContextStorage.run(
//        { tenantId: req.tenantId, actorId: req.user?.id, ip: req.ip },
//        () => next(),
//      );
// 3. For unauthenticated routes (login, OTP request), actorId will be undefined —
//    the audit extension writes `actor_id: null` in that case, which is allowed
//    (see AuditLog.actorId being optional in prisma/schema.prisma).
// 4. For background jobs / seed scripts that mutate sensitive models outside an
//    HTTP request, wrap the call manually, e.g.:
//      auditContextStorage.run({ tenantId, actorId: "system" }, () => prisma.user.update(...));

import { AsyncLocalStorage } from "node:async_hooks";

export interface AuditContext {
  /** Tenant the current request/operation is scoped to. */
  tenantId?: string;
  /** Acting user id (uuid). Undefined for unauthenticated/system operations. */
  actorId?: string;
  /** Originating IP, if available (for audit_logs.ip). */
  ip?: string;
  /**
   * Opaque request correlation id (e.g. UUID from X-Request-Id header or
   * generated by AuditContextMiddleware). Optional — present when a request
   * id is available; used for log correlation and test fixture tracing.
   */
  requestId?: string;
}

export const auditContextStorage = new AsyncLocalStorage<AuditContext>();

/** Reads the current audit context, or an empty object outside any `.run()` scope. */
export function getAuditContext(): AuditContext {
  return auditContextStorage.getStore() ?? {};
}
